language: c

env:
  global:
    - RTRAVISPATH=~root/R-travis
    - RTRAVISR="install_github(c('assertthat', 'testthat', 'bigrquery')); " # add custom R code to be executed before installing package
  matrix:
    - RTRAVISTYPE=quick
    - RTRAVISTYPE=full

# install dependencies
install:
  - sudo git clone https://github.com/krlmlr/R-travis.git $RTRAVISPATH
  - sudo -E $RTRAVISPATH/r-travis install

# run tests
script:
  - $RTRAVISPATH/r-travis test
